# Keyword sets for classification. 

MOVING_FORWARD_KEYWORDS = {"time sensitive", 
                           "next steps on your application", 
                           "Onboarding", 
                           "still missing", 
                           "requirements", 
                           "please", 
                           "complete", 
                           "still interested", 
                           "moving forward", 
                           "test", 
                           "as soon as possible", 
                           "48 hs", 
                           "48h", 
                           "48 h", 
                           "48hs",
                           "24hs", 
                           "24 hs", 
                           "24 h", 
                           "24h", 
                           "job description", 
                           "link", 
                           "important", 
                           "results", 
                           "reply", 
                           "confirm", 
                           "confirmation", 
                           "confirmación", 
                           "entrevista técnica", 
                           "entrevista", 
                           "técnica", 
                           "interview", 
                           "reunion", 
                           "reunión", 
                           "call", 
                           "llamada", 
                           "horarios", 
                           "group", 
                           "grupal", 
                           "individual", 
                           "next step", 
                           "siguiente paso", 
                           "propuesta", 
                           "próximos pasos", 
                           "equipo", 
                           "tareas", 
                           "tasks", 
                           "task", 
                           "within", 
                           "salary", 
                           "USD", 
                           "ARS", 
                           "próximo paso", 
                           "próximo", 
                           "hs", 
                           "teams", 
                           "Teams", 
                           "encuentro", 
                           "minutos", 
                           "brief", 
                           "Google Meets", 
                           "te esperamos"}


REJECTION_KEYWORDS = {"unfortunately", 
                      "not to move forward", 
                      "desafortunadamente", 
                      "no seguir con tu proceso de selección", 
                      "have moved forward", "other candidates", 
                      "continue seeking", 
                      "pero agradecemos", 
                      "no", 
                      "hemos decidido no seguir con tu proceso de selección", 
                      "more closely align with", 
                      "encorauge", 
                      "better match"}


NEUTRAL_KEYWORDS = {"participar en la conversación", 
                    "artículo", 
                    "submitted successfully", 
                    "we wanted to share with you some of our latest job opportunities", 
                    "Ahora sigue estos pasos para llegar aún más lejos", 
                    "descubre empleos similares", 
                    "verify your", 
                    "account", 
                    "Se ha enviado tu solicitud a"}